version: '3.9'
services:
  web:
    build: ./web
    command: npm run start
    environment:
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
      - ALGO_USD_FALLBACK=${ALGO_USD_FALLBACK}
    ports: [ "3001:3001" ]
    depends_on: [ bot ]

  bot:
    build: ./bot
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - REDIS_URL=${REDIS_URL}
      - BOT_TOKEN=${BOT_TOKEN}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
      - NODELY_INDEXER_URL=${NODELY_INDEXER_URL}
      - NODELY_INDEXER_API_KEY=${NODELY_INDEXER_API_KEY}
      - ALGORAND_NODE_URL=${ALGORAND_NODE_URL}
      - TINYMAN_API=${TINYMAN_API}
      - ETHEREUM_RPC_URL=${ETHEREUM_RPC_URL}
      - SOLANA_RPC_URL=${SOLANA_RPC_URL}
      - ROLE_CITIZEN_ID=${ROLE_CITIZEN_ID}
      - ROLE_HODL_SHRIMP_ID=${ROLE_HODL_SHRIMP_ID}
      - ROLE_HODL_CRAB_ID=${ROLE_HODL_CRAB_ID}
      - ROLE_HODL_FISH_ID=${ROLE_HODL_FISH_ID}
      - ROLE_HODL_DOLPHIN_ID=${ROLE_HODL_DOLPHIN_ID}
      - ROLE_HODL_SHARK_ID=${ROLE_HODL_SHARK_ID}
      - ROLE_HODL_WHALE_ID=${ROLE_HODL_WHALE_ID}
      - ROLE_HODL_TITAN_ID=${ROLE_HODL_TITAN_ID}
      - ALG_BALANCE_TTL_MS=${ALG_BALANCE_TTL_MS}
      - BUCKETS=${BUCKETS}
      - BUCKET_PERIOD_MIN=${BUCKET_PERIOD_MIN}
      - SCAN_CONCURRENCY=${SCAN_CONCURRENCY}
      - SCAN_SPACING_MS=${SCAN_SPACING_MS}
      - GLOBAL_CALL_BUDGET_5M=${GLOBAL_CALL_BUDGET_5M}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS}
      - RATE_LIMIT_MAX_TOKENS=${RATE_LIMIT_MAX_TOKENS}
      - RATE_LIMIT_REFILL_PER_SEC=${RATE_LIMIT_REFILL_PER_SEC}
      - RATE_LIMIT_BURST=${RATE_LIMIT_BURST}
      - ADMIN_RATE_LIMIT_WINDOW_MS=${ADMIN_RATE_LIMIT_WINDOW_MS}
      - ADMIN_RATE_LIMIT_MAX_TOKENS=${ADMIN_RATE_LIMIT_MAX_TOKENS}
      - ADMIN_RATE_LIMIT_REFILL_PER_SEC=${ADMIN_RATE_LIMIT_REFILL_PER_SEC}
      - ADMIN_RATE_LIMIT_BURST=${ADMIN_RATE_LIMIT_BURST}
      - ADMIN_IP_ALLOWLIST=${ADMIN_IP_ALLOWLIST}
      - ENABLE_TINYMAN=${ENABLE_TINYMAN}
      - ENABLE_PACT=${ENABLE_PACT}
      - PACT_API_BASE=${PACT_API_BASE}
      - REP_V2_TTL_SECS=${REP_V2_TTL_SECS}
      - LP_SNAPSHOT_TTL_SECS=${LP_SNAPSHOT_TTL_SECS}
    ports: [ "3000:3000" ]
