services:
  - type: web
    name: h4c-web
    env: node
    rootDir: web
    buildCommand: |
      echo "Node version:" && node --version &&
      echo "Installing dependencies..." && npm install &&
      echo "Building web app..." && npm run build
    startCommand: "npm run start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "18.17.0"
      - key: NEXT_PUBLIC_SITE_URL
        value: https://hunger4crypto.com
      - key: ALGO_USD_FALLBACK
        value: "0.20"
      - key: PORT
        value: "3001"
      # Add fallback values to prevent build failures
      - key: BOT_API_URL
        value: "http://localhost:3000"
    autoDeploy: true
    
  - type: web
    name: h4c-bot
    env: node
    rootDir: bot
    buildCommand: |
      echo "Node version:" && node --version &&
      echo "Installing dependencies..." && npm install &&
      echo "Checking environment..." && node -e "console.log('Env check passed')"
    startCommand: "npm run start"
    healthCheckPath: "/health"
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "18.17.0"
      - key: PORT
        value: "3000"
      
      # CRITICAL: These MUST be set in Render dashboard
      - key: MONGODB_URI
        sync: false
      - key: REDIS_URL
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: DISCORD_GUILD_ID
        sync: false
      - key: ADMIN_JWT_SECRET
        sync: false
      - key: ALGORAND_NODE_URL
        value: "https://mainnet-api.algonode.cloud"
      
      # Optional with sensible defaults
      - key: NODELY_INDEXER_URL
        value: "https://mainnet-api.4160.nodely.dev"
      - key: TINYMAN_API
        value: "https://mainnet.analytics.tinyman.org/api/v1"
      
      # Performance settings
      - key: ALG_BALANCE_TTL_MS
        value: "60000"
      - key: BUCKETS
        value: "10"
      - key: BUCKET_PERIOD_MIN
        value: "5"
      - key: SCAN_CONCURRENCY
        value: "3"
      - key: SCAN_SPACING_MS
        value: "1000"
      - key: GLOBAL_CALL_BUDGET_5M
        value: "300"
      - key: ENABLE_TINYMAN
        value: "true"
      - key: ENABLE_PACT
        value: "false"
      
      # Rate limiting  
      - key: RATE_LIMIT_WINDOW_MS
        value: "60000"
      - key: RATE_LIMIT_MAX_TOKENS
        value: "120"
      - key: RATE_LIMIT_REFILL_PER_SEC
        value: "2"
      - key: RATE_LIMIT_BURST
        value: "20"
      - key: ADMIN_RATE_LIMIT_WINDOW_MS
        value: "60000"
      - key: ADMIN_RATE_LIMIT_MAX_TOKENS
        value: "30"
      - key: ADMIN_RATE_LIMIT_REFILL_PER_SEC
        value: "1"
      - key: ADMIN_RATE_LIMIT_BURST
        value: "5"
      
      # Defaults for optional features
      - key: REP_V2_TTL_SECS
        value: "900"
      - key: LP_SNAPSHOT_TTL_SECS
        value: "7200"
      - key: LOG_LEVEL
        value: "info"
        
    autoDeploy: true
