services:
  - type: web
    name: h4c-web
    env: node
    rootDir: web
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SITE_URL
        value: https://hunger4crypto.com
      - key: ALGO_USD_FALLBACK
        value: "0.20"
      - key: PORT
        value: "3001"
    autoDeploy: true
    
  - type: web
    name: h4c-bot
    env: node
    rootDir: bot
    buildCommand: "npm install"
    startCommand: "npm run start"
    healthCheckPath: "/health"
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: REDIS_URL
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: DISCORD_GUILD_ID
        sync: false
      - key: ADMIN_JWT_SECRET
        sync: false
      - key: NODELY_INDEXER_URL
        sync: false
      - key: NODELY_INDEXER_API_KEY
        sync: false
      - key: ALGORAND_NODE_URL
        sync: false
      - key: TINYMAN_API
        value: "https://mainnet.analytics.tinyman.org/api/v1"
      - key: ETHEREUM_RPC_URL
        sync: false
      - key: SOLANA_RPC_URL
        sync: false
      - key: ALG_BALANCE_TTL_MS
        value: "60000"
      - key: BUCKETS
        value: "10"
      - key: BUCKET_PERIOD_MIN
        value: "5"
      - key: SCAN_CONCURRENCY
        value: "3"
      - key: SCAN_SPACING_MS
        value: "1000"
      - key: GLOBAL_CALL_BUDGET_5M
        value: "300"
      - key: ENABLE_TINYMAN
        value: "true"
      - key: ENABLE_PACT
        value: "false"
    autoDeploy: true
