services:
  # === Web Frontend (Next.js) ===
  - type: web
    name: h4c-web
    env: node
    plan: starter  # Free tier
    buildCommand: ./scripts/render-build.sh
    startCommand: cd web && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "18.20.5"
      - key: PORT
        value: "10000"
      - key: NEXT_PUBLIC_SITE_URL
        fromService:
          type: web
          name: h4c-web
          property: host
      - key: ALGO_USD_FALLBACK
        value: "0.20"
    autoDeploy: true

  # === Discord Bot Worker ===
  - type: worker
    name: h4c-bot
    env: node
    plan: starter  # Free tier
    buildCommand: ./scripts/render-worker-build.sh
    startCommand: cd bot && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: LOG_LEVEL
        value: info
      - key: ENABLE_HTTP
        value: "false"
      - key: PORT
        value: "10000"

      # === REQUIRED SECRETS (Set in Render UI) ===
      - key: BOT_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: REDIS_URL
        sync: false
      - key: DISCORD_GUILD_ID
        sync: false
      - key: ADMIN_JWT_SECRET
        sync: false

      # === OPTIONAL API KEYS ===
      - key: NODELY_INDEXER_API_KEY
        sync: false
      - key: ETHEREUM_RPC_URL
        sync: false
      - key: SOLANA_RPC_URL
        sync: false

      # === DISCORD ROLES (Optional) ===
      - key: ROLE_CITIZEN_ID
        sync: false
      - key: ROLE_HODL_SHRIMP_ID
        sync: false
      - key: ROLE_HODL_CRAB_ID
        sync: false
      - key: ROLE_HODL_FISH_ID
        sync: false
      - key: ROLE_HODL_DOLPHIN_ID
        sync: false
      - key: ROLE_HODL_SHARK_ID
        sync: false
      - key: ROLE_HODL_WHALE_ID
        sync: false
      - key: ROLE_HODL_TITAN_ID
        sync: false

      # === SAFE DEFAULTS ===
      - key: ALGORAND_NODE_URL
        value: "https://mainnet-api.algonode.cloud"
      - key: NODELY_INDEXER_URL
        value: "https://mainnet-api.4160.nodely.dev"
      - key: TINYMAN_API
        value: "https://mainnet.analytics.tinyman.org/api/v1"
      - key: ALG_BALANCE_TTL_MS
        value: "60000"
      - key: BUCKETS
        value: "10"
      - key: BUCKET_PERIOD_MIN
        value: "5"
      - key: SCAN_CONCURRENCY
        value: "3"
      - key: SCAN_SPACING_MS
        value: "1000"
      - key: GLOBAL_CALL_BUDGET_5M
        value: "300"
      - key: RATE_LIMIT_WINDOW_MS
        value: "60000"
      - key: RATE_LIMIT_MAX_TOKENS
        value: "120"
      - key: RATE_LIMIT_REFILL_PER_SEC
        value: "2"
      - key: RATE_LIMIT_BURST
        value: "20"
      - key: ADMIN_RATE_LIMIT_WINDOW_MS
        value: "60000"
      - key: ADMIN_RATE_LIMIT_MAX_TOKENS
        value: "30"
      - key: ADMIN_RATE_LIMIT_REFILL_PER_SEC
        value: "1"
      - key: ADMIN_RATE_LIMIT_BURST
        value: "5"
      - key: ADMIN_IP_ALLOWLIST
        value: "127.0.0.1,10.0.0"
      - key: ENABLE_TINYMAN
        value: "true"
      - key: ENABLE_PACT
        value: "false"
      - key: PACT_API_BASE
        value: ""
      - key: REP_V2_TTL_SECS
        value: "900"
      - key: LP_SNAPSHOT_TTL_SECS
        value: "7200"
    autoDeploy: true
