services:
  - type: worker
    name: h4c-bot
    env: node
    plan: starter
    
    # Build with memory limits
    buildCommand: |
      export NODE_OPTIONS="--max-old-space-size=256"
      cd shared && npm ci --production
      cd ../bot && npm ci --production
    
    # Start with memory constraints
    startCommand: |
      cd bot && node --max-old-space-size=384 --expose-gc src/index.js
    
    envVars:
      - key: NODE_ENV
        value: production
      
      - key: NODE_OPTIONS
        value: "--max-old-space-size=384"
      
      # Reduce connection pools
      - key: DB_POOL_SIZE
        value: "2"
      
      - key: REDIS_MAX_RETRIES
        value: "1"
      
      # Disable memory-heavy features
      - key: ENABLE_AUTO_AWARDS
        value: "false"
      
      - key: ENABLE_METRICS
        value: "false"
      
      - key: ENABLE_LEADERBOARDS
        value: "false"
      
      - key: ENABLE_ADVANCED_LOGGING
        value: "false"
      
      # Required
      - key: BOT_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: REDIS_URL
        sync: false
      - key: DISCORD_GUILD_ID
        sync: false
      - key: ADMIN_JWT_SECRET
        sync: false
    
    # Auto-restart if it crashes
    autoDeploy: true
    
    # Health check
    healthCheckPath: /health
